# Generated by Django 6.0.5 on 2026-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('code_snippet', models.TextField(blank=True, null=True, verbose_name='Код JavaScript (необязательно)')),
                ('difficulty', models.IntegerField(choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3'), (4, 'Уровень 4'), (5, 'Уровень 5')], default=3, verbose_name='Сложность (1-5)')),
                ('topic', models.CharField(max_length=100, verbose_name='Тема (например: closures, async)')),
                ('option_a', models.CharField(max_length=255, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Вариант C')),
                ('correct_option', models.CharField(choices=[('A', 'Вариант A'), ('B', 'Вариант B'), ('C', 'Вариант C')], max_length=1, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
