# Generated by Django 6.0.5 on 2026-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснение / Разбор вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3'), (4, 'Уровень 4'), (5, 'Уровень 5'), (6, 'Уровень 6'), (7, 'Уровень 7'), (8, 'Уровень 8'), (9, 'Уровень 9'), (10, 'Уровень 10'), (11, 'Уровень 11'), (12, 'Уровень 12'), (13, 'Уровень 13'), (14, 'Уровень 14'), (15, 'Уровень 15'), (16, 'Уровень 16'), (17, 'Уровень 17'), (18, 'Уровень 18'), (19, 'Уровень 19'), (20, 'Уровень 20'), (21, 'Уровень 21'), (22, 'Уровень 22'), (23, 'Уровень 23'), (24, 'Уровень 24'), (25, 'Уровень 25')], default=12, verbose_name='Сложность (1-25)'),
        ),
    ]
