# Generated by Django 6.0.5 on 2026-06-03 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_explanation_alter_question_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterField(
            model_name='question',
            name='code_snippet',
            field=models.TextField(blank=True, null=True, verbose_name='Код/Листинг'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(verbose_name='Сложность (1-25)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=255, verbose_name='Вариант А'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=255, verbose_name='Вариант Б'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=255, verbose_name='Вариант С'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема вопроса'),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Правильных ответов')),
                ('final_level', models.IntegerField(verbose_name='Финальный уровень сложности')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Тест сгенерирован ИИ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса на момент прохождения')),
                ('selected_option', models.CharField(max_length=10, verbose_name='Выбранный вариант')),
                ('status', models.CharField(max_length=20, verbose_name='Статус (correct/incorrect/dont_know)')),
                ('difficulty_at_time', models.IntegerField(verbose_name='Сложность вопроса')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.testsession', verbose_name='Сессия тестирования')),
            ],
        ),
    ]
